environment:
  APPVEYOR_RDP_PASSWORD: 01Winter
  access_token: 
    secure: ESG3buBaoWKVM85+BE6rd6NcBcn/Zvam6C2YFkOycad0IVQE7zUgrDNoFJamuKw9

init:
  #Good practice because Windows line ending is different from Unix/Linux's
  - git config --global core.autocrlf true
  
install:
  - ps: Write-Host "Install R..."
  - choco install R
  - ps: Write-Host "R is installed."
  
  - ps: Write-Host "Install pandoc..."
  - choco install pandoc
  - ps: Write-Host "pandoc is installed"
  
#  - ps: Write-Host "Install rmarkdown..."
#  - ps: & "C:\Program Files\R\R-3.6.1\bin\rscript.exe" -e "install.packages('rmarkdown', repos='http://cran.case.edu/')"
#  - ps: Write-Host "rmarkdown is installed"
  
#  - ps: Write-Host "Install bookdown..."
#  - ps: & "C:\Program Files\R\R-3.6.1\bin\rscript.exe" -e "install.packages('bookdown', repos='http://cran.case.edu/')"
#  - ps: Write-Host "bookdown is installed"

#  - ps: Write-Host "Install reticulate..."
#  - ps: & "C:\\Program Files\\R\\R-3.6.1\\bin\\rscript.exe" -e "install.packages('reticulate', repos='http://cran.case.edu/')"
#  - ps: Write-Host "reticulate is installed"  

build_script:
  - git checkout master
  - ps: .\build.ps1
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_success:
#  - git config --global credential.helper store
#  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"  
#  - git config --global user.email "jinjie_liu@fas.harvard.edu"
#  - git config --global user.name "liujinjie111"
#  - git add docs
#  - git commit -m "publish new book"
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#  - git push origin head:master