# Set Up an AWS Account

The first thing to do is to create your very own AWS account. Amazon updates the Management Console screens frequently, so the instructions may be different than what you see displayed on your terminal.

1.	Point your favorite web browser to the main **Amazon Web Services page** at `http://aws.amazon.com`.
2.	Choose **Create an AWS Account**.
3.	Enter a **username**, your **e-mail address**, and the **password** you want to use. Then choose **Continue**.
4.	Choose **Personal** or **Professional**.  
**Note:** Personal accounts and professional accounts have the same features and functions.
5.	On the Account Information screen, enter your **address** and **phone number** information. You’re asked to select the box confirming that you agree to the terms of the AWS customer agreement.
6.	Enter the required **personal information**, confirm your **acceptance** of the customer agreement, and then click the **Create Account** and **Continue** button.  
**Note:** You receive an email to confirm that your account is created. You can sign in to your new account using the email address and password you supplied. However, you can't use AWS services until you finish activating your account.
7.	Enter the required **payment information** in the appropriate fields and then choose **Secure Submit**.
8.	**Verify** your phone number
    + Choose whether you want to verify your account by **Text message (SMS)** or a **Voice call**.
    + Choose your country or region code from the list.
    + Enter a phone number where you can be reached in the next few minutes.
    + Enter the code displayed in the captcha.
    + When you're ready, choose Contact me. In a few moments, an automated system will contact you.  
    **Note:** If you chose to verify your account by SMS, choose **Send SMS** instead.
    + Enter the PIN you receive by text message or voice call, and then choose **Continue**.
9.	On the **Select a Support Plan page**, choose one of the available Support plans. For a description of the available Support plans and their benefits, see [Compare AWS Support Plans](https://aws.amazon.com/premiumsupport/plans/).
10.	After you choose a Support plan, a confirmation page indicates that your account is being activated. Accounts are usually activated within a few minutes, but the process might take up to 24 hours. You can sign in to your AWS account during this time. The AWS home page might display a button that shows "Complete Sign Up" during this time, even if you've completed all the steps in the sign-up process.
11.	When your account is fully activated, you'll receive a confirmation email. After you receive this email, you have full access to all AWS services.
