# Get the Results Locally

112.	You could copy the results printed out in the **Output cell** in the Jupyter notebook and paste it to an editor locally.
113.	To download files or folders in S3 bucket to local, open the **Amazon S3 console**.
114.	In the **Bucket name** list, choose the name of the bucket that you want to download an object from.
115.	In the **Name** list, select the check box next to the object you want to download, and then choose **Download** on the object description page that appears.

**Congratulations! You are done. To clean up your environment, do the following:**

116.	To sign out of the **Jupyter notebook**, click **Logout**.
117.	To clean up the S3 bucket objects after downloading, open the **Amazon S3 console**. In the **Bucket name** list, choose the name of the bucket that you want to delete an object from. In the **Name** list, select the check box next to the objects and folders that you want to delete, choose **Delete**.
118.	If you don’t need the instance anymore, open the Amazon EC2 console **Instances page**. In the **Name** list, select the instance that you want to do the operation. **Right click** on the instance. In the **Instance State** drop-down menu, either **stop** or **terminate** the instance. The instance state status will change in a few minutes. 
119.	To sign out of **AWS Management Console**, click on your **username** at the top of the console, and then click **Sign Out**. 
